// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NFSLGDefine.proto

#include "NFSLGDefine.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_NFMsgBase_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_NFMsgBase_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Ident;
}  // namespace protobuf_NFMsgBase_2eproto
namespace NFMsg {
class ReqAckBuyObjectFormShopDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqAckBuyObjectFormShop>
      _instance;
} _ReqAckBuyObjectFormShop_default_instance_;
class ReqAckMoveBuildObjectDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqAckMoveBuildObject>
      _instance;
} _ReqAckMoveBuildObject_default_instance_;
class ReqUpBuildLvDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqUpBuildLv>
      _instance;
} _ReqUpBuildLv_default_instance_;
class ReqCreateItemDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqCreateItem>
      _instance;
} _ReqCreateItem_default_instance_;
class ReqBuildOperateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqBuildOperate>
      _instance;
} _ReqBuildOperate_default_instance_;
}  // namespace NFMsg
namespace protobuf_NFSLGDefine_2eproto {
static void InitDefaultsReqAckBuyObjectFormShop() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::NFMsg::_ReqAckBuyObjectFormShop_default_instance_;
    new (ptr) ::NFMsg::ReqAckBuyObjectFormShop();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::NFMsg::ReqAckBuyObjectFormShop::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqAckBuyObjectFormShop =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqAckBuyObjectFormShop}, {}};

static void InitDefaultsReqAckMoveBuildObject() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::NFMsg::_ReqAckMoveBuildObject_default_instance_;
    new (ptr) ::NFMsg::ReqAckMoveBuildObject();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::NFMsg::ReqAckMoveBuildObject::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ReqAckMoveBuildObject =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsReqAckMoveBuildObject}, {
      &protobuf_NFMsgBase_2eproto::scc_info_Ident.base,}};

static void InitDefaultsReqUpBuildLv() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::NFMsg::_ReqUpBuildLv_default_instance_;
    new (ptr) ::NFMsg::ReqUpBuildLv();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::NFMsg::ReqUpBuildLv::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ReqUpBuildLv =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsReqUpBuildLv}, {
      &protobuf_NFMsgBase_2eproto::scc_info_Ident.base,}};

static void InitDefaultsReqCreateItem() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::NFMsg::_ReqCreateItem_default_instance_;
    new (ptr) ::NFMsg::ReqCreateItem();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::NFMsg::ReqCreateItem::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ReqCreateItem =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsReqCreateItem}, {
      &protobuf_NFMsgBase_2eproto::scc_info_Ident.base,}};

static void InitDefaultsReqBuildOperate() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::NFMsg::_ReqBuildOperate_default_instance_;
    new (ptr) ::NFMsg::ReqBuildOperate();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::NFMsg::ReqBuildOperate::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ReqBuildOperate =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsReqBuildOperate}, {
      &protobuf_NFMsgBase_2eproto::scc_info_Ident.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReqAckBuyObjectFormShop.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqAckMoveBuildObject.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqUpBuildLv.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqCreateItem.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqBuildOperate.base);
}

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, config_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckBuyObjectFormShop, shop_id_),
  0,
  2,
  3,
  4,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, row_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, object_guid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqAckMoveBuildObject, z_),
  1,
  0,
  2,
  3,
  4,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqUpBuildLv, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqUpBuildLv, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqUpBuildLv, row_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqUpBuildLv, object_guid_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqCreateItem, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqCreateItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqCreateItem, row_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqCreateItem, object_guid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqCreateItem, config_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqCreateItem, count_),
  2,
  1,
  0,
  3,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqBuildOperate, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqBuildOperate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqBuildOperate, row_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqBuildOperate, object_guid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NFMsg::ReqBuildOperate, functype_),
  1,
  0,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::NFMsg::ReqAckBuyObjectFormShop)},
  { 15, 25, sizeof(::NFMsg::ReqAckMoveBuildObject)},
  { 30, 37, sizeof(::NFMsg::ReqUpBuildLv)},
  { 39, 48, sizeof(::NFMsg::ReqCreateItem)},
  { 52, 60, sizeof(::NFMsg::ReqBuildOperate)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::NFMsg::_ReqAckBuyObjectFormShop_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::NFMsg::_ReqAckMoveBuildObject_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::NFMsg::_ReqUpBuildLv_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::NFMsg::_ReqCreateItem_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::NFMsg::_ReqBuildOperate_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "NFSLGDefine.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021NFSLGDefine.proto\022\005NFMsg\032\017NFMsgBase.pr"
      "oto\"^\n\027ReqAckBuyObjectFormShop\022\021\n\tconfig"
      "_id\030\001 \002(\t\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022\t\n\001z\030\004 \002"
      "(\002\022\017\n\007Shop_id\030\005 \002(\t\"h\n\025ReqAckMoveBuildOb"
      "ject\022\013\n\003row\030\001 \001(\005\022!\n\013object_guid\030\002 \002(\0132\014"
      ".NFMsg.Ident\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 \002(\002\022\t\n\001z\030"
      "\005 \002(\002\">\n\014ReqUpBuildLv\022\013\n\003row\030\001 \001(\005\022!\n\013ob"
      "ject_guid\030\002 \002(\0132\014.NFMsg.Ident\"a\n\rReqCrea"
      "teItem\022\013\n\003row\030\001 \001(\005\022!\n\013object_guid\030\002 \002(\013"
      "2\014.NFMsg.Ident\022\021\n\tconfig_id\030\003 \002(\t\022\r\n\005cou"
      "nt\030\004 \002(\005\"h\n\017ReqBuildOperate\022\013\n\003row\030\001 \001(\005"
      "\022!\n\013object_guid\030\002 \002(\0132\014.NFMsg.Ident\022%\n\010f"
      "unctype\030\003 \002(\0162\023.NFMsg.ESLGFuncType*\201\001\n\020E"
      "SLGBuildingType\022\014\n\010EBT_BASE\020\000\022\017\n\013EBT_DEF"
      "ENSE\020\001\022\014\n\010EBT_ARMY\020\002\022\020\n\014EBT_RESOURCE\020\003\022\r"
      "\n\tEBT_GUILD\020\004\022\016\n\nEBT_TEMPLE\020\005\022\017\n\013EBT_NUC"
      "LEAR\020\006*\200\010\n\023ESLGBuildingSubType\022\r\n\tEBST_H"
      "ALL\020\000\022\021\n\rEBST_MASHROOM\020F\022\r\n\tEBST_BUSH\020G\022"
      "\021\n\rEBST_BRANCH_1\020H\022\021\n\rEBST_BRANCH_2\020I\022\021\n"
      "\rEBST_BRANCH_3\020J\022\017\n\013EBST_TREE_1\020K\022\017\n\013EBS"
      "T_TREE_2\020L\022\017\n\013EBST_TREE_3\020M\022\020\n\014EBST_STON"
      "E_1\020N\022\020\n\014EBST_STONE_2\020O\022\020\n\014EBST_STONE_3\020"
      "P\022\r\n\tEBST_TOMB\020Q\022\022\n\016EBST_DARK_TOMB\020R\022\016\n\n"
      "EBST_PYXIS\020S\022\016\n\nEBST_TORCH\020T\022\024\n\020EBST__WH"
      "ITE_FLAG\020U\022\017\n\013EBST_CANNON\020e\022\017\n\013EBST_MORT"
      "AR\020f\022\025\n\021EBST_ARCHER_TOWER\020g\022\025\n\021EBST_WIZA"
      "RD_TOWER\020h\022\022\n\016EBST_AIR_TOWER\020i\022\024\n\020EBST_T"
      "ESLA_TOWER\020j\022\r\n\tEBST_WALL\020k\022\016\n\nEBST_X_BO"
      "W\020l\022\r\n\tEBST_BOMB\020m\022\021\n\rEBST_AIR_BOMB\020n\022\024\n"
      "\020EBST_SPRING_TRAP\020o\022\023\n\017EBST_HELL_TOWER\020p"
      "\022\016\n\tEBST_CAMP\020\310\001\022\021\n\014EBST_BARRACK\020\311\001\022\025\n\020E"
      "BST_TEC_FACTORY\020\312\001\022\026\n\021EBST_DARK_BARRACK\020"
      "\313\001\022\026\n\021EBST_DRUG_FACTORY\020\314\001\022\024\n\017EBST_KING_"
      "ALTAR\020\315\001\022\025\n\020EBST_QUEEN_ALTAR\020\316\001\022\030\n\023EBST_"
      "GOLD_COLLECTOR\020\254\002\022\026\n\021EBST_GOLD_STORAGE\020\255"
      "\002\022\031\n\024EBST_STONE_COLLECTOR\020\256\002\022\027\n\022EBST_STO"
      "NE_STORAGE\020\257\002\022\031\n\024EBST_STEEL_COLLECTOR\020\260\002"
      "\022\027\n\022EBST_STEEL_STORAGE\020\261\002\022\033\n\026EBST_DIAMON"
      "D_COLLECTOR\020\262\002\022\031\n\024EBST_DIAMOND_STORAGE\020\263"
      "\002\022\r\n\010EBST_HUT\020\264\002\022\026\n\021EBST_GUILD_CASTLE\020\220\003"
      "\022\025\n\020EBST_GUILD_CRYPT\020\221\003\022\025\n\020EBST_ELEMENT_"
      "LAB\020\364\003\022\031\n\024EBST_NUCLEAR_FACTORY\020\330\004*\370\001\n\014ES"
      "LGArmyType\022\017\n\013EAT_FOOTMAN\020\000\022\016\n\nEAT_ARCHE"
      "R\020\001\022\016\n\nEAT_GOBLIN\020\002\022\r\n\tEAT_GIANT\020\003\022\024\n\020EA"
      "T_WALL_BREAKER\020\004\022\017\n\013EAT_BALLOON\020\005\022\016\n\nEAT"
      "_HEALER\020\006\022\016\n\nEAT_WIZARD\020\007\022\016\n\nEAT_DRAGON\020"
      "\010\022\r\n\tEAT_PEKKA\020\t\022\016\n\nEAT_MINION\020\024\022\021\n\rEAT_"
      "HOG_RIDER\020\025\022\020\n\014EAT_VALKYRIE\020\026\022\r\n\tEAT_GOL"
      "EM\020\027*\225\002\n\014ESLGFuncType\022\014\n\010EFT_INFO\020\000\022\016\n\nE"
      "FT_BOOOST\020\001\022\r\n\tEFT_LVLUP\020\002\022\025\n\021EFT_CREATE"
      "_SOLDER\020\003\022\024\n\020EFT_CREATE_SPEEL\020\004\022\020\n\014EFT_R"
      "ESEARCH\020\005\022\024\n\020EFT_COLLECT_GOLD\020\006\022\025\n\021EFT_C"
      "OLLECT_STONE\020\007\022\025\n\021EFT_COLLECT_STEEL\020\010\022\027\n"
      "\023EFT_COLLECT_DIAMOND\020\t\022\014\n\010EFT_SELL\020\n\022\016\n\n"
      "EFT_REPAIR\020\013\022\016\n\nEFT_CANCEL\020\014\022\016\n\nEFT_FINI"
      "SH\020\r*A\n\021ESLGBuildingState\022\014\n\010EBS_IDLE\020\000\022"
      "\r\n\tEBS_BOOST\020\001\022\017\n\013EBS_UPGRADE\020\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 2271);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NFSLGDefine.proto", &protobuf_RegisterTypes);
  ::protobuf_NFMsgBase_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_NFSLGDefine_2eproto
namespace NFMsg {
const ::google::protobuf::EnumDescriptor* ESLGBuildingType_descriptor() {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NFSLGDefine_2eproto::file_level_enum_descriptors[0];
}
bool ESLGBuildingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESLGBuildingSubType_descriptor() {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NFSLGDefine_2eproto::file_level_enum_descriptors[1];
}
bool ESLGBuildingSubType_IsValid(int value) {
  switch (value) {
    case 0:
    case 70:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 78:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 106:
    case 107:
    case 108:
    case 109:
    case 110:
    case 111:
    case 112:
    case 200:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 206:
    case 300:
    case 301:
    case 302:
    case 303:
    case 304:
    case 305:
    case 306:
    case 307:
    case 308:
    case 400:
    case 401:
    case 500:
    case 600:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESLGArmyType_descriptor() {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NFSLGDefine_2eproto::file_level_enum_descriptors[2];
}
bool ESLGArmyType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESLGFuncType_descriptor() {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NFSLGDefine_2eproto::file_level_enum_descriptors[3];
}
bool ESLGFuncType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESLGBuildingState_descriptor() {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NFSLGDefine_2eproto::file_level_enum_descriptors[4];
}
bool ESLGBuildingState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ReqAckBuyObjectFormShop::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqAckBuyObjectFormShop::kConfigIdFieldNumber;
const int ReqAckBuyObjectFormShop::kXFieldNumber;
const int ReqAckBuyObjectFormShop::kYFieldNumber;
const int ReqAckBuyObjectFormShop::kZFieldNumber;
const int ReqAckBuyObjectFormShop::kShopIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqAckBuyObjectFormShop::ReqAckBuyObjectFormShop()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NFSLGDefine_2eproto::scc_info_ReqAckBuyObjectFormShop.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:NFMsg.ReqAckBuyObjectFormShop)
}
ReqAckBuyObjectFormShop::ReqAckBuyObjectFormShop(const ReqAckBuyObjectFormShop& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  config_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_config_id()) {
    config_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.config_id_);
  }
  shop_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_shop_id()) {
    shop_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shop_id_);
  }
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:NFMsg.ReqAckBuyObjectFormShop)
}

void ReqAckBuyObjectFormShop::SharedCtor() {
  config_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  shop_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

ReqAckBuyObjectFormShop::~ReqAckBuyObjectFormShop() {
  // @@protoc_insertion_point(destructor:NFMsg.ReqAckBuyObjectFormShop)
  SharedDtor();
}

void ReqAckBuyObjectFormShop::SharedDtor() {
  config_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  shop_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReqAckBuyObjectFormShop::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqAckBuyObjectFormShop::descriptor() {
  ::protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqAckBuyObjectFormShop& ReqAckBuyObjectFormShop::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NFSLGDefine_2eproto::scc_info_ReqAckBuyObjectFormShop.base);
  return *internal_default_instance();
}


void ReqAckBuyObjectFormShop::Clear() {
// @@protoc_insertion_point(message_clear_start:NFMsg.ReqAckBuyObjectFormShop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      config_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      shop_id_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 28u) {
    ::memset(&x_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&z_) -
        reinterpret_cast<char*>(&x_)) + sizeof(z_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ReqAckBuyObjectFormShop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NFMsg.ReqAckBuyObjectFormShop)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string config_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_config_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->config_id().data(), static_cast<int>(this->config_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "NFMsg.ReqAckBuyObjectFormShop.config_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float x = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          set_has_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float y = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          set_has_y();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float z = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {
          set_has_z();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string Shop_id = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_shop_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->shop_id().data(), static_cast<int>(this->shop_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "NFMsg.ReqAckBuyObjectFormShop.Shop_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NFMsg.ReqAckBuyObjectFormShop)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NFMsg.ReqAckBuyObjectFormShop)
  return false;
#undef DO_
}

void ReqAckBuyObjectFormShop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NFMsg.ReqAckBuyObjectFormShop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string config_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->config_id().data(), static_cast<int>(this->config_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "NFMsg.ReqAckBuyObjectFormShop.config_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->config_id(), output);
  }

  // required float x = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // required float y = 3;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  // required float z = 4;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->z(), output);
  }

  // required string Shop_id = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->shop_id().data(), static_cast<int>(this->shop_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "NFMsg.ReqAckBuyObjectFormShop.Shop_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->shop_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NFMsg.ReqAckBuyObjectFormShop)
}

::google::protobuf::uint8* ReqAckBuyObjectFormShop::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NFMsg.ReqAckBuyObjectFormShop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string config_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->config_id().data(), static_cast<int>(this->config_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "NFMsg.ReqAckBuyObjectFormShop.config_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->config_id(), target);
  }

  // required float x = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // required float y = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  // required float z = 4;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->z(), target);
  }

  // required string Shop_id = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->shop_id().data(), static_cast<int>(this->shop_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "NFMsg.ReqAckBuyObjectFormShop.Shop_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->shop_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NFMsg.ReqAckBuyObjectFormShop)
  return target;
}

size_t ReqAckBuyObjectFormShop::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:NFMsg.ReqAckBuyObjectFormShop)
  size_t total_size = 0;

  if (has_config_id()) {
    // required string config_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->config_id());
  }

  if (has_shop_id()) {
    // required string Shop_id = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->shop_id());
  }

  if (has_x()) {
    // required float x = 2;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 3;
    total_size += 1 + 4;
  }

  if (has_z()) {
    // required float z = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
size_t ReqAckBuyObjectFormShop::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NFMsg.ReqAckBuyObjectFormShop)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required string config_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->config_id());

    // required string Shop_id = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->shop_id());

    // required float x = 2;
    total_size += 1 + 4;

    // required float y = 3;
    total_size += 1 + 4;

    // required float z = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqAckBuyObjectFormShop::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NFMsg.ReqAckBuyObjectFormShop)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqAckBuyObjectFormShop* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqAckBuyObjectFormShop>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NFMsg.ReqAckBuyObjectFormShop)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NFMsg.ReqAckBuyObjectFormShop)
    MergeFrom(*source);
  }
}

void ReqAckBuyObjectFormShop::MergeFrom(const ReqAckBuyObjectFormShop& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NFMsg.ReqAckBuyObjectFormShop)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_config_id();
      config_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.config_id_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_shop_id();
      shop_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shop_id_);
    }
    if (cached_has_bits & 0x00000004u) {
      x_ = from.x_;
    }
    if (cached_has_bits & 0x00000008u) {
      y_ = from.y_;
    }
    if (cached_has_bits & 0x00000010u) {
      z_ = from.z_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReqAckBuyObjectFormShop::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NFMsg.ReqAckBuyObjectFormShop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqAckBuyObjectFormShop::CopyFrom(const ReqAckBuyObjectFormShop& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NFMsg.ReqAckBuyObjectFormShop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqAckBuyObjectFormShop::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;
  return true;
}

void ReqAckBuyObjectFormShop::Swap(ReqAckBuyObjectFormShop* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqAckBuyObjectFormShop::InternalSwap(ReqAckBuyObjectFormShop* other) {
  using std::swap;
  config_id_.Swap(&other->config_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  shop_id_.Swap(&other->shop_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqAckBuyObjectFormShop::GetMetadata() const {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqAckMoveBuildObject::InitAsDefaultInstance() {
  ::NFMsg::_ReqAckMoveBuildObject_default_instance_._instance.get_mutable()->object_guid_ = const_cast< ::NFMsg::Ident*>(
      ::NFMsg::Ident::internal_default_instance());
}
void ReqAckMoveBuildObject::clear_object_guid() {
  if (object_guid_ != NULL) object_guid_->Clear();
  clear_has_object_guid();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqAckMoveBuildObject::kRowFieldNumber;
const int ReqAckMoveBuildObject::kObjectGuidFieldNumber;
const int ReqAckMoveBuildObject::kXFieldNumber;
const int ReqAckMoveBuildObject::kYFieldNumber;
const int ReqAckMoveBuildObject::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqAckMoveBuildObject::ReqAckMoveBuildObject()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NFSLGDefine_2eproto::scc_info_ReqAckMoveBuildObject.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:NFMsg.ReqAckMoveBuildObject)
}
ReqAckMoveBuildObject::ReqAckMoveBuildObject(const ReqAckMoveBuildObject& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_object_guid()) {
    object_guid_ = new ::NFMsg::Ident(*from.object_guid_);
  } else {
    object_guid_ = NULL;
  }
  ::memcpy(&row_, &from.row_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&row_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:NFMsg.ReqAckMoveBuildObject)
}

void ReqAckMoveBuildObject::SharedCtor() {
  ::memset(&object_guid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&object_guid_)) + sizeof(z_));
}

ReqAckMoveBuildObject::~ReqAckMoveBuildObject() {
  // @@protoc_insertion_point(destructor:NFMsg.ReqAckMoveBuildObject)
  SharedDtor();
}

void ReqAckMoveBuildObject::SharedDtor() {
  if (this != internal_default_instance()) delete object_guid_;
}

void ReqAckMoveBuildObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqAckMoveBuildObject::descriptor() {
  ::protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqAckMoveBuildObject& ReqAckMoveBuildObject::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NFSLGDefine_2eproto::scc_info_ReqAckMoveBuildObject.base);
  return *internal_default_instance();
}


void ReqAckMoveBuildObject::Clear() {
// @@protoc_insertion_point(message_clear_start:NFMsg.ReqAckMoveBuildObject)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(object_guid_ != NULL);
    object_guid_->Clear();
  }
  if (cached_has_bits & 30u) {
    ::memset(&row_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&z_) -
        reinterpret_cast<char*>(&row_)) + sizeof(z_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ReqAckMoveBuildObject::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NFMsg.ReqAckMoveBuildObject)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 row = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_row();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &row_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .NFMsg.Ident object_guid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_object_guid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float x = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          set_has_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float y = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {
          set_has_y();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float z = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {
          set_has_z();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NFMsg.ReqAckMoveBuildObject)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NFMsg.ReqAckMoveBuildObject)
  return false;
#undef DO_
}

void ReqAckMoveBuildObject::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NFMsg.ReqAckMoveBuildObject)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->row(), output);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_object_guid(), output);
  }

  // required float x = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->x(), output);
  }

  // required float y = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->y(), output);
  }

  // required float z = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->z(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NFMsg.ReqAckMoveBuildObject)
}

::google::protobuf::uint8* ReqAckMoveBuildObject::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NFMsg.ReqAckMoveBuildObject)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->row(), target);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_object_guid(), deterministic, target);
  }

  // required float x = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->x(), target);
  }

  // required float y = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->y(), target);
  }

  // required float z = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->z(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NFMsg.ReqAckMoveBuildObject)
  return target;
}

size_t ReqAckMoveBuildObject::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:NFMsg.ReqAckMoveBuildObject)
  size_t total_size = 0;

  if (has_object_guid()) {
    // required .NFMsg.Ident object_guid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);
  }

  if (has_x()) {
    // required float x = 3;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 4;
    total_size += 1 + 4;
  }

  if (has_z()) {
    // required float z = 5;
    total_size += 1 + 4;
  }

  return total_size;
}
size_t ReqAckMoveBuildObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NFMsg.ReqAckMoveBuildObject)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000001d) ^ 0x0000001d) == 0) {  // All required fields are present.
    // required .NFMsg.Ident object_guid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);

    // required float x = 3;
    total_size += 1 + 4;

    // required float y = 4;
    total_size += 1 + 4;

    // required float z = 5;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional int32 row = 1;
  if (has_row()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->row());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqAckMoveBuildObject::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NFMsg.ReqAckMoveBuildObject)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqAckMoveBuildObject* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqAckMoveBuildObject>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NFMsg.ReqAckMoveBuildObject)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NFMsg.ReqAckMoveBuildObject)
    MergeFrom(*source);
  }
}

void ReqAckMoveBuildObject::MergeFrom(const ReqAckMoveBuildObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NFMsg.ReqAckMoveBuildObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_object_guid()->::NFMsg::Ident::MergeFrom(from.object_guid());
    }
    if (cached_has_bits & 0x00000002u) {
      row_ = from.row_;
    }
    if (cached_has_bits & 0x00000004u) {
      x_ = from.x_;
    }
    if (cached_has_bits & 0x00000008u) {
      y_ = from.y_;
    }
    if (cached_has_bits & 0x00000010u) {
      z_ = from.z_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReqAckMoveBuildObject::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NFMsg.ReqAckMoveBuildObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqAckMoveBuildObject::CopyFrom(const ReqAckMoveBuildObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NFMsg.ReqAckMoveBuildObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqAckMoveBuildObject::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001d) != 0x0000001d) return false;
  if (has_object_guid()) {
    if (!this->object_guid_->IsInitialized()) return false;
  }
  return true;
}

void ReqAckMoveBuildObject::Swap(ReqAckMoveBuildObject* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqAckMoveBuildObject::InternalSwap(ReqAckMoveBuildObject* other) {
  using std::swap;
  swap(object_guid_, other->object_guid_);
  swap(row_, other->row_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqAckMoveBuildObject::GetMetadata() const {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqUpBuildLv::InitAsDefaultInstance() {
  ::NFMsg::_ReqUpBuildLv_default_instance_._instance.get_mutable()->object_guid_ = const_cast< ::NFMsg::Ident*>(
      ::NFMsg::Ident::internal_default_instance());
}
void ReqUpBuildLv::clear_object_guid() {
  if (object_guid_ != NULL) object_guid_->Clear();
  clear_has_object_guid();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqUpBuildLv::kRowFieldNumber;
const int ReqUpBuildLv::kObjectGuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqUpBuildLv::ReqUpBuildLv()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NFSLGDefine_2eproto::scc_info_ReqUpBuildLv.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:NFMsg.ReqUpBuildLv)
}
ReqUpBuildLv::ReqUpBuildLv(const ReqUpBuildLv& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_object_guid()) {
    object_guid_ = new ::NFMsg::Ident(*from.object_guid_);
  } else {
    object_guid_ = NULL;
  }
  row_ = from.row_;
  // @@protoc_insertion_point(copy_constructor:NFMsg.ReqUpBuildLv)
}

void ReqUpBuildLv::SharedCtor() {
  ::memset(&object_guid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&row_) -
      reinterpret_cast<char*>(&object_guid_)) + sizeof(row_));
}

ReqUpBuildLv::~ReqUpBuildLv() {
  // @@protoc_insertion_point(destructor:NFMsg.ReqUpBuildLv)
  SharedDtor();
}

void ReqUpBuildLv::SharedDtor() {
  if (this != internal_default_instance()) delete object_guid_;
}

void ReqUpBuildLv::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqUpBuildLv::descriptor() {
  ::protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqUpBuildLv& ReqUpBuildLv::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NFSLGDefine_2eproto::scc_info_ReqUpBuildLv.base);
  return *internal_default_instance();
}


void ReqUpBuildLv::Clear() {
// @@protoc_insertion_point(message_clear_start:NFMsg.ReqUpBuildLv)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(object_guid_ != NULL);
    object_guid_->Clear();
  }
  row_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ReqUpBuildLv::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NFMsg.ReqUpBuildLv)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 row = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_row();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &row_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .NFMsg.Ident object_guid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_object_guid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NFMsg.ReqUpBuildLv)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NFMsg.ReqUpBuildLv)
  return false;
#undef DO_
}

void ReqUpBuildLv::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NFMsg.ReqUpBuildLv)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->row(), output);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_object_guid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NFMsg.ReqUpBuildLv)
}

::google::protobuf::uint8* ReqUpBuildLv::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NFMsg.ReqUpBuildLv)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->row(), target);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_object_guid(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NFMsg.ReqUpBuildLv)
  return target;
}

size_t ReqUpBuildLv::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NFMsg.ReqUpBuildLv)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required .NFMsg.Ident object_guid = 2;
  if (has_object_guid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);
  }
  // optional int32 row = 1;
  if (has_row()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->row());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqUpBuildLv::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NFMsg.ReqUpBuildLv)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqUpBuildLv* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqUpBuildLv>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NFMsg.ReqUpBuildLv)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NFMsg.ReqUpBuildLv)
    MergeFrom(*source);
  }
}

void ReqUpBuildLv::MergeFrom(const ReqUpBuildLv& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NFMsg.ReqUpBuildLv)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_object_guid()->::NFMsg::Ident::MergeFrom(from.object_guid());
    }
    if (cached_has_bits & 0x00000002u) {
      row_ = from.row_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReqUpBuildLv::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NFMsg.ReqUpBuildLv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqUpBuildLv::CopyFrom(const ReqUpBuildLv& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NFMsg.ReqUpBuildLv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqUpBuildLv::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (has_object_guid()) {
    if (!this->object_guid_->IsInitialized()) return false;
  }
  return true;
}

void ReqUpBuildLv::Swap(ReqUpBuildLv* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqUpBuildLv::InternalSwap(ReqUpBuildLv* other) {
  using std::swap;
  swap(object_guid_, other->object_guid_);
  swap(row_, other->row_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqUpBuildLv::GetMetadata() const {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqCreateItem::InitAsDefaultInstance() {
  ::NFMsg::_ReqCreateItem_default_instance_._instance.get_mutable()->object_guid_ = const_cast< ::NFMsg::Ident*>(
      ::NFMsg::Ident::internal_default_instance());
}
void ReqCreateItem::clear_object_guid() {
  if (object_guid_ != NULL) object_guid_->Clear();
  clear_has_object_guid();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqCreateItem::kRowFieldNumber;
const int ReqCreateItem::kObjectGuidFieldNumber;
const int ReqCreateItem::kConfigIdFieldNumber;
const int ReqCreateItem::kCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqCreateItem::ReqCreateItem()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NFSLGDefine_2eproto::scc_info_ReqCreateItem.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:NFMsg.ReqCreateItem)
}
ReqCreateItem::ReqCreateItem(const ReqCreateItem& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  config_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_config_id()) {
    config_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.config_id_);
  }
  if (from.has_object_guid()) {
    object_guid_ = new ::NFMsg::Ident(*from.object_guid_);
  } else {
    object_guid_ = NULL;
  }
  ::memcpy(&row_, &from.row_,
    static_cast<size_t>(reinterpret_cast<char*>(&count_) -
    reinterpret_cast<char*>(&row_)) + sizeof(count_));
  // @@protoc_insertion_point(copy_constructor:NFMsg.ReqCreateItem)
}

void ReqCreateItem::SharedCtor() {
  config_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&object_guid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&count_) -
      reinterpret_cast<char*>(&object_guid_)) + sizeof(count_));
}

ReqCreateItem::~ReqCreateItem() {
  // @@protoc_insertion_point(destructor:NFMsg.ReqCreateItem)
  SharedDtor();
}

void ReqCreateItem::SharedDtor() {
  config_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete object_guid_;
}

void ReqCreateItem::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqCreateItem::descriptor() {
  ::protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqCreateItem& ReqCreateItem::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NFSLGDefine_2eproto::scc_info_ReqCreateItem.base);
  return *internal_default_instance();
}


void ReqCreateItem::Clear() {
// @@protoc_insertion_point(message_clear_start:NFMsg.ReqCreateItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      config_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(object_guid_ != NULL);
      object_guid_->Clear();
    }
  }
  if (cached_has_bits & 12u) {
    ::memset(&row_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&count_) -
        reinterpret_cast<char*>(&row_)) + sizeof(count_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ReqCreateItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NFMsg.ReqCreateItem)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 row = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_row();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &row_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .NFMsg.Ident object_guid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_object_guid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string config_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_config_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->config_id().data(), static_cast<int>(this->config_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "NFMsg.ReqCreateItem.config_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 count = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_count();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NFMsg.ReqCreateItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NFMsg.ReqCreateItem)
  return false;
#undef DO_
}

void ReqCreateItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NFMsg.ReqCreateItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->row(), output);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_object_guid(), output);
  }

  // required string config_id = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->config_id().data(), static_cast<int>(this->config_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "NFMsg.ReqCreateItem.config_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->config_id(), output);
  }

  // required int32 count = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->count(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NFMsg.ReqCreateItem)
}

::google::protobuf::uint8* ReqCreateItem::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NFMsg.ReqCreateItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->row(), target);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_object_guid(), deterministic, target);
  }

  // required string config_id = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->config_id().data(), static_cast<int>(this->config_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "NFMsg.ReqCreateItem.config_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->config_id(), target);
  }

  // required int32 count = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->count(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NFMsg.ReqCreateItem)
  return target;
}

size_t ReqCreateItem::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:NFMsg.ReqCreateItem)
  size_t total_size = 0;

  if (has_config_id()) {
    // required string config_id = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->config_id());
  }

  if (has_object_guid()) {
    // required .NFMsg.Ident object_guid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);
  }

  if (has_count()) {
    // required int32 count = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->count());
  }

  return total_size;
}
size_t ReqCreateItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NFMsg.ReqCreateItem)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000b) ^ 0x0000000b) == 0) {  // All required fields are present.
    // required string config_id = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->config_id());

    // required .NFMsg.Ident object_guid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);

    // required int32 count = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->count());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional int32 row = 1;
  if (has_row()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->row());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqCreateItem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NFMsg.ReqCreateItem)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqCreateItem* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqCreateItem>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NFMsg.ReqCreateItem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NFMsg.ReqCreateItem)
    MergeFrom(*source);
  }
}

void ReqCreateItem::MergeFrom(const ReqCreateItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NFMsg.ReqCreateItem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_config_id();
      config_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.config_id_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_object_guid()->::NFMsg::Ident::MergeFrom(from.object_guid());
    }
    if (cached_has_bits & 0x00000004u) {
      row_ = from.row_;
    }
    if (cached_has_bits & 0x00000008u) {
      count_ = from.count_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReqCreateItem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NFMsg.ReqCreateItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqCreateItem::CopyFrom(const ReqCreateItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NFMsg.ReqCreateItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqCreateItem::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000b) != 0x0000000b) return false;
  if (has_object_guid()) {
    if (!this->object_guid_->IsInitialized()) return false;
  }
  return true;
}

void ReqCreateItem::Swap(ReqCreateItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqCreateItem::InternalSwap(ReqCreateItem* other) {
  using std::swap;
  config_id_.Swap(&other->config_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(object_guid_, other->object_guid_);
  swap(row_, other->row_);
  swap(count_, other->count_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqCreateItem::GetMetadata() const {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqBuildOperate::InitAsDefaultInstance() {
  ::NFMsg::_ReqBuildOperate_default_instance_._instance.get_mutable()->object_guid_ = const_cast< ::NFMsg::Ident*>(
      ::NFMsg::Ident::internal_default_instance());
}
void ReqBuildOperate::clear_object_guid() {
  if (object_guid_ != NULL) object_guid_->Clear();
  clear_has_object_guid();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqBuildOperate::kRowFieldNumber;
const int ReqBuildOperate::kObjectGuidFieldNumber;
const int ReqBuildOperate::kFunctypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqBuildOperate::ReqBuildOperate()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NFSLGDefine_2eproto::scc_info_ReqBuildOperate.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:NFMsg.ReqBuildOperate)
}
ReqBuildOperate::ReqBuildOperate(const ReqBuildOperate& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_object_guid()) {
    object_guid_ = new ::NFMsg::Ident(*from.object_guid_);
  } else {
    object_guid_ = NULL;
  }
  ::memcpy(&row_, &from.row_,
    static_cast<size_t>(reinterpret_cast<char*>(&functype_) -
    reinterpret_cast<char*>(&row_)) + sizeof(functype_));
  // @@protoc_insertion_point(copy_constructor:NFMsg.ReqBuildOperate)
}

void ReqBuildOperate::SharedCtor() {
  ::memset(&object_guid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&functype_) -
      reinterpret_cast<char*>(&object_guid_)) + sizeof(functype_));
}

ReqBuildOperate::~ReqBuildOperate() {
  // @@protoc_insertion_point(destructor:NFMsg.ReqBuildOperate)
  SharedDtor();
}

void ReqBuildOperate::SharedDtor() {
  if (this != internal_default_instance()) delete object_guid_;
}

void ReqBuildOperate::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqBuildOperate::descriptor() {
  ::protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqBuildOperate& ReqBuildOperate::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NFSLGDefine_2eproto::scc_info_ReqBuildOperate.base);
  return *internal_default_instance();
}


void ReqBuildOperate::Clear() {
// @@protoc_insertion_point(message_clear_start:NFMsg.ReqBuildOperate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(object_guid_ != NULL);
    object_guid_->Clear();
  }
  if (cached_has_bits & 6u) {
    ::memset(&row_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&functype_) -
        reinterpret_cast<char*>(&row_)) + sizeof(functype_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ReqBuildOperate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NFMsg.ReqBuildOperate)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 row = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_row();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &row_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .NFMsg.Ident object_guid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_object_guid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .NFMsg.ESLGFuncType functype = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::NFMsg::ESLGFuncType_IsValid(value)) {
            set_functype(static_cast< ::NFMsg::ESLGFuncType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NFMsg.ReqBuildOperate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NFMsg.ReqBuildOperate)
  return false;
#undef DO_
}

void ReqBuildOperate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NFMsg.ReqBuildOperate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->row(), output);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_object_guid(), output);
  }

  // required .NFMsg.ESLGFuncType functype = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->functype(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NFMsg.ReqBuildOperate)
}

::google::protobuf::uint8* ReqBuildOperate::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NFMsg.ReqBuildOperate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 row = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->row(), target);
  }

  // required .NFMsg.Ident object_guid = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_object_guid(), deterministic, target);
  }

  // required .NFMsg.ESLGFuncType functype = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->functype(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NFMsg.ReqBuildOperate)
  return target;
}

size_t ReqBuildOperate::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:NFMsg.ReqBuildOperate)
  size_t total_size = 0;

  if (has_object_guid()) {
    // required .NFMsg.Ident object_guid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);
  }

  if (has_functype()) {
    // required .NFMsg.ESLGFuncType functype = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->functype());
  }

  return total_size;
}
size_t ReqBuildOperate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NFMsg.ReqBuildOperate)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000005) ^ 0x00000005) == 0) {  // All required fields are present.
    // required .NFMsg.Ident object_guid = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *object_guid_);

    // required .NFMsg.ESLGFuncType functype = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->functype());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional int32 row = 1;
  if (has_row()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->row());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqBuildOperate::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NFMsg.ReqBuildOperate)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqBuildOperate* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqBuildOperate>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NFMsg.ReqBuildOperate)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NFMsg.ReqBuildOperate)
    MergeFrom(*source);
  }
}

void ReqBuildOperate::MergeFrom(const ReqBuildOperate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NFMsg.ReqBuildOperate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_object_guid()->::NFMsg::Ident::MergeFrom(from.object_guid());
    }
    if (cached_has_bits & 0x00000002u) {
      row_ = from.row_;
    }
    if (cached_has_bits & 0x00000004u) {
      functype_ = from.functype_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReqBuildOperate::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NFMsg.ReqBuildOperate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqBuildOperate::CopyFrom(const ReqBuildOperate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NFMsg.ReqBuildOperate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqBuildOperate::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;
  if (has_object_guid()) {
    if (!this->object_guid_->IsInitialized()) return false;
  }
  return true;
}

void ReqBuildOperate::Swap(ReqBuildOperate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqBuildOperate::InternalSwap(ReqBuildOperate* other) {
  using std::swap;
  swap(object_guid_, other->object_guid_);
  swap(row_, other->row_);
  swap(functype_, other->functype_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqBuildOperate::GetMetadata() const {
  protobuf_NFSLGDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NFSLGDefine_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace NFMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::NFMsg::ReqAckBuyObjectFormShop* Arena::CreateMaybeMessage< ::NFMsg::ReqAckBuyObjectFormShop >(Arena* arena) {
  return Arena::CreateInternal< ::NFMsg::ReqAckBuyObjectFormShop >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::NFMsg::ReqAckMoveBuildObject* Arena::CreateMaybeMessage< ::NFMsg::ReqAckMoveBuildObject >(Arena* arena) {
  return Arena::CreateInternal< ::NFMsg::ReqAckMoveBuildObject >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::NFMsg::ReqUpBuildLv* Arena::CreateMaybeMessage< ::NFMsg::ReqUpBuildLv >(Arena* arena) {
  return Arena::CreateInternal< ::NFMsg::ReqUpBuildLv >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::NFMsg::ReqCreateItem* Arena::CreateMaybeMessage< ::NFMsg::ReqCreateItem >(Arena* arena) {
  return Arena::CreateInternal< ::NFMsg::ReqCreateItem >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::NFMsg::ReqBuildOperate* Arena::CreateMaybeMessage< ::NFMsg::ReqBuildOperate >(Arena* arena) {
  return Arena::CreateInternal< ::NFMsg::ReqBuildOperate >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
