// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NFSLGDefine.proto

#ifndef PROTOBUF_INCLUDED_NFSLGDefine_2eproto
#define PROTOBUF_INCLUDED_NFSLGDefine_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "NFMsgBase.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_NFSLGDefine_2eproto 

namespace protobuf_NFSLGDefine_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_NFSLGDefine_2eproto
namespace NFMsg {
class ReqAckBuyObjectFormShop;
class ReqAckBuyObjectFormShopDefaultTypeInternal;
extern ReqAckBuyObjectFormShopDefaultTypeInternal _ReqAckBuyObjectFormShop_default_instance_;
class ReqAckMoveBuildObject;
class ReqAckMoveBuildObjectDefaultTypeInternal;
extern ReqAckMoveBuildObjectDefaultTypeInternal _ReqAckMoveBuildObject_default_instance_;
class ReqBuildOperate;
class ReqBuildOperateDefaultTypeInternal;
extern ReqBuildOperateDefaultTypeInternal _ReqBuildOperate_default_instance_;
class ReqCreateItem;
class ReqCreateItemDefaultTypeInternal;
extern ReqCreateItemDefaultTypeInternal _ReqCreateItem_default_instance_;
class ReqUpBuildLv;
class ReqUpBuildLvDefaultTypeInternal;
extern ReqUpBuildLvDefaultTypeInternal _ReqUpBuildLv_default_instance_;
}  // namespace NFMsg
namespace google {
namespace protobuf {
template<> ::NFMsg::ReqAckBuyObjectFormShop* Arena::CreateMaybeMessage<::NFMsg::ReqAckBuyObjectFormShop>(Arena*);
template<> ::NFMsg::ReqAckMoveBuildObject* Arena::CreateMaybeMessage<::NFMsg::ReqAckMoveBuildObject>(Arena*);
template<> ::NFMsg::ReqBuildOperate* Arena::CreateMaybeMessage<::NFMsg::ReqBuildOperate>(Arena*);
template<> ::NFMsg::ReqCreateItem* Arena::CreateMaybeMessage<::NFMsg::ReqCreateItem>(Arena*);
template<> ::NFMsg::ReqUpBuildLv* Arena::CreateMaybeMessage<::NFMsg::ReqUpBuildLv>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace NFMsg {

enum ESLGBuildingType {
  EBT_BASE = 0,
  EBT_DEFENSE = 1,
  EBT_ARMY = 2,
  EBT_RESOURCE = 3,
  EBT_GUILD = 4,
  EBT_TEMPLE = 5,
  EBT_NUCLEAR = 6
};
bool ESLGBuildingType_IsValid(int value);
const ESLGBuildingType ESLGBuildingType_MIN = EBT_BASE;
const ESLGBuildingType ESLGBuildingType_MAX = EBT_NUCLEAR;
const int ESLGBuildingType_ARRAYSIZE = ESLGBuildingType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ESLGBuildingType_descriptor();
inline const ::std::string& ESLGBuildingType_Name(ESLGBuildingType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ESLGBuildingType_descriptor(), value);
}
inline bool ESLGBuildingType_Parse(
    const ::std::string& name, ESLGBuildingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ESLGBuildingType>(
    ESLGBuildingType_descriptor(), name, value);
}
enum ESLGBuildingSubType {
  EBST_HALL = 0,
  EBST_MASHROOM = 70,
  EBST_BUSH = 71,
  EBST_BRANCH_1 = 72,
  EBST_BRANCH_2 = 73,
  EBST_BRANCH_3 = 74,
  EBST_TREE_1 = 75,
  EBST_TREE_2 = 76,
  EBST_TREE_3 = 77,
  EBST_STONE_1 = 78,
  EBST_STONE_2 = 79,
  EBST_STONE_3 = 80,
  EBST_TOMB = 81,
  EBST_DARK_TOMB = 82,
  EBST_PYXIS = 83,
  EBST_TORCH = 84,
  EBST__WHITE_FLAG = 85,
  EBST_CANNON = 101,
  EBST_MORTAR = 102,
  EBST_ARCHER_TOWER = 103,
  EBST_WIZARD_TOWER = 104,
  EBST_AIR_TOWER = 105,
  EBST_TESLA_TOWER = 106,
  EBST_WALL = 107,
  EBST_X_BOW = 108,
  EBST_BOMB = 109,
  EBST_AIR_BOMB = 110,
  EBST_SPRING_TRAP = 111,
  EBST_HELL_TOWER = 112,
  EBST_CAMP = 200,
  EBST_BARRACK = 201,
  EBST_TEC_FACTORY = 202,
  EBST_DARK_BARRACK = 203,
  EBST_DRUG_FACTORY = 204,
  EBST_KING_ALTAR = 205,
  EBST_QUEEN_ALTAR = 206,
  EBST_GOLD_COLLECTOR = 300,
  EBST_GOLD_STORAGE = 301,
  EBST_STONE_COLLECTOR = 302,
  EBST_STONE_STORAGE = 303,
  EBST_STEEL_COLLECTOR = 304,
  EBST_STEEL_STORAGE = 305,
  EBST_DIAMOND_COLLECTOR = 306,
  EBST_DIAMOND_STORAGE = 307,
  EBST_HUT = 308,
  EBST_GUILD_CASTLE = 400,
  EBST_GUILD_CRYPT = 401,
  EBST_ELEMENT_LAB = 500,
  EBST_NUCLEAR_FACTORY = 600
};
bool ESLGBuildingSubType_IsValid(int value);
const ESLGBuildingSubType ESLGBuildingSubType_MIN = EBST_HALL;
const ESLGBuildingSubType ESLGBuildingSubType_MAX = EBST_NUCLEAR_FACTORY;
const int ESLGBuildingSubType_ARRAYSIZE = ESLGBuildingSubType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ESLGBuildingSubType_descriptor();
inline const ::std::string& ESLGBuildingSubType_Name(ESLGBuildingSubType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ESLGBuildingSubType_descriptor(), value);
}
inline bool ESLGBuildingSubType_Parse(
    const ::std::string& name, ESLGBuildingSubType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ESLGBuildingSubType>(
    ESLGBuildingSubType_descriptor(), name, value);
}
enum ESLGArmyType {
  EAT_FOOTMAN = 0,
  EAT_ARCHER = 1,
  EAT_GOBLIN = 2,
  EAT_GIANT = 3,
  EAT_WALL_BREAKER = 4,
  EAT_BALLOON = 5,
  EAT_HEALER = 6,
  EAT_WIZARD = 7,
  EAT_DRAGON = 8,
  EAT_PEKKA = 9,
  EAT_MINION = 20,
  EAT_HOG_RIDER = 21,
  EAT_VALKYRIE = 22,
  EAT_GOLEM = 23
};
bool ESLGArmyType_IsValid(int value);
const ESLGArmyType ESLGArmyType_MIN = EAT_FOOTMAN;
const ESLGArmyType ESLGArmyType_MAX = EAT_GOLEM;
const int ESLGArmyType_ARRAYSIZE = ESLGArmyType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ESLGArmyType_descriptor();
inline const ::std::string& ESLGArmyType_Name(ESLGArmyType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ESLGArmyType_descriptor(), value);
}
inline bool ESLGArmyType_Parse(
    const ::std::string& name, ESLGArmyType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ESLGArmyType>(
    ESLGArmyType_descriptor(), name, value);
}
enum ESLGFuncType {
  EFT_INFO = 0,
  EFT_BOOOST = 1,
  EFT_LVLUP = 2,
  EFT_CREATE_SOLDER = 3,
  EFT_CREATE_SPEEL = 4,
  EFT_RESEARCH = 5,
  EFT_COLLECT_GOLD = 6,
  EFT_COLLECT_STONE = 7,
  EFT_COLLECT_STEEL = 8,
  EFT_COLLECT_DIAMOND = 9,
  EFT_SELL = 10,
  EFT_REPAIR = 11,
  EFT_CANCEL = 12,
  EFT_FINISH = 13
};
bool ESLGFuncType_IsValid(int value);
const ESLGFuncType ESLGFuncType_MIN = EFT_INFO;
const ESLGFuncType ESLGFuncType_MAX = EFT_FINISH;
const int ESLGFuncType_ARRAYSIZE = ESLGFuncType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ESLGFuncType_descriptor();
inline const ::std::string& ESLGFuncType_Name(ESLGFuncType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ESLGFuncType_descriptor(), value);
}
inline bool ESLGFuncType_Parse(
    const ::std::string& name, ESLGFuncType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ESLGFuncType>(
    ESLGFuncType_descriptor(), name, value);
}
enum ESLGBuildingState {
  EBS_IDLE = 0,
  EBS_BOOST = 1,
  EBS_UPGRADE = 2
};
bool ESLGBuildingState_IsValid(int value);
const ESLGBuildingState ESLGBuildingState_MIN = EBS_IDLE;
const ESLGBuildingState ESLGBuildingState_MAX = EBS_UPGRADE;
const int ESLGBuildingState_ARRAYSIZE = ESLGBuildingState_MAX + 1;

const ::google::protobuf::EnumDescriptor* ESLGBuildingState_descriptor();
inline const ::std::string& ESLGBuildingState_Name(ESLGBuildingState value) {
  return ::google::protobuf::internal::NameOfEnum(
    ESLGBuildingState_descriptor(), value);
}
inline bool ESLGBuildingState_Parse(
    const ::std::string& name, ESLGBuildingState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ESLGBuildingState>(
    ESLGBuildingState_descriptor(), name, value);
}
// ===================================================================

class ReqAckBuyObjectFormShop : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NFMsg.ReqAckBuyObjectFormShop) */ {
 public:
  ReqAckBuyObjectFormShop();
  virtual ~ReqAckBuyObjectFormShop();

  ReqAckBuyObjectFormShop(const ReqAckBuyObjectFormShop& from);

  inline ReqAckBuyObjectFormShop& operator=(const ReqAckBuyObjectFormShop& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqAckBuyObjectFormShop(ReqAckBuyObjectFormShop&& from) noexcept
    : ReqAckBuyObjectFormShop() {
    *this = ::std::move(from);
  }

  inline ReqAckBuyObjectFormShop& operator=(ReqAckBuyObjectFormShop&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqAckBuyObjectFormShop& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqAckBuyObjectFormShop* internal_default_instance() {
    return reinterpret_cast<const ReqAckBuyObjectFormShop*>(
               &_ReqAckBuyObjectFormShop_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReqAckBuyObjectFormShop* other);
  friend void swap(ReqAckBuyObjectFormShop& a, ReqAckBuyObjectFormShop& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqAckBuyObjectFormShop* New() const final {
    return CreateMaybeMessage<ReqAckBuyObjectFormShop>(NULL);
  }

  ReqAckBuyObjectFormShop* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqAckBuyObjectFormShop>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqAckBuyObjectFormShop& from);
  void MergeFrom(const ReqAckBuyObjectFormShop& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqAckBuyObjectFormShop* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string config_id = 1;
  bool has_config_id() const;
  void clear_config_id();
  static const int kConfigIdFieldNumber = 1;
  const ::std::string& config_id() const;
  void set_config_id(const ::std::string& value);
  #if LANG_CXX11
  void set_config_id(::std::string&& value);
  #endif
  void set_config_id(const char* value);
  void set_config_id(const char* value, size_t size);
  ::std::string* mutable_config_id();
  ::std::string* release_config_id();
  void set_allocated_config_id(::std::string* config_id);

  // required string Shop_id = 5;
  bool has_shop_id() const;
  void clear_shop_id();
  static const int kShopIdFieldNumber = 5;
  const ::std::string& shop_id() const;
  void set_shop_id(const ::std::string& value);
  #if LANG_CXX11
  void set_shop_id(::std::string&& value);
  #endif
  void set_shop_id(const char* value);
  void set_shop_id(const char* value, size_t size);
  ::std::string* mutable_shop_id();
  ::std::string* release_shop_id();
  void set_allocated_shop_id(::std::string* shop_id);

  // required float x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  float x() const;
  void set_x(float value);

  // required float y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  float y() const;
  void set_y(float value);

  // required float z = 4;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 4;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:NFMsg.ReqAckBuyObjectFormShop)
 private:
  void set_has_config_id();
  void clear_has_config_id();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_shop_id();
  void clear_has_shop_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr config_id_;
  ::google::protobuf::internal::ArenaStringPtr shop_id_;
  float x_;
  float y_;
  float z_;
  friend struct ::protobuf_NFSLGDefine_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqAckMoveBuildObject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NFMsg.ReqAckMoveBuildObject) */ {
 public:
  ReqAckMoveBuildObject();
  virtual ~ReqAckMoveBuildObject();

  ReqAckMoveBuildObject(const ReqAckMoveBuildObject& from);

  inline ReqAckMoveBuildObject& operator=(const ReqAckMoveBuildObject& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqAckMoveBuildObject(ReqAckMoveBuildObject&& from) noexcept
    : ReqAckMoveBuildObject() {
    *this = ::std::move(from);
  }

  inline ReqAckMoveBuildObject& operator=(ReqAckMoveBuildObject&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqAckMoveBuildObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqAckMoveBuildObject* internal_default_instance() {
    return reinterpret_cast<const ReqAckMoveBuildObject*>(
               &_ReqAckMoveBuildObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ReqAckMoveBuildObject* other);
  friend void swap(ReqAckMoveBuildObject& a, ReqAckMoveBuildObject& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqAckMoveBuildObject* New() const final {
    return CreateMaybeMessage<ReqAckMoveBuildObject>(NULL);
  }

  ReqAckMoveBuildObject* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqAckMoveBuildObject>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqAckMoveBuildObject& from);
  void MergeFrom(const ReqAckMoveBuildObject& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqAckMoveBuildObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .NFMsg.Ident object_guid = 2;
  bool has_object_guid() const;
  void clear_object_guid();
  static const int kObjectGuidFieldNumber = 2;
  private:
  const ::NFMsg::Ident& _internal_object_guid() const;
  public:
  const ::NFMsg::Ident& object_guid() const;
  ::NFMsg::Ident* release_object_guid();
  ::NFMsg::Ident* mutable_object_guid();
  void set_allocated_object_guid(::NFMsg::Ident* object_guid);

  // optional int32 row = 1;
  bool has_row() const;
  void clear_row();
  static const int kRowFieldNumber = 1;
  ::google::protobuf::int32 row() const;
  void set_row(::google::protobuf::int32 value);

  // required float x = 3;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 3;
  float x() const;
  void set_x(float value);

  // required float y = 4;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 4;
  float y() const;
  void set_y(float value);

  // required float z = 5;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 5;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:NFMsg.ReqAckMoveBuildObject)
 private:
  void set_has_row();
  void clear_has_row();
  void set_has_object_guid();
  void clear_has_object_guid();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::NFMsg::Ident* object_guid_;
  ::google::protobuf::int32 row_;
  float x_;
  float y_;
  float z_;
  friend struct ::protobuf_NFSLGDefine_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqUpBuildLv : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NFMsg.ReqUpBuildLv) */ {
 public:
  ReqUpBuildLv();
  virtual ~ReqUpBuildLv();

  ReqUpBuildLv(const ReqUpBuildLv& from);

  inline ReqUpBuildLv& operator=(const ReqUpBuildLv& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqUpBuildLv(ReqUpBuildLv&& from) noexcept
    : ReqUpBuildLv() {
    *this = ::std::move(from);
  }

  inline ReqUpBuildLv& operator=(ReqUpBuildLv&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqUpBuildLv& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqUpBuildLv* internal_default_instance() {
    return reinterpret_cast<const ReqUpBuildLv*>(
               &_ReqUpBuildLv_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ReqUpBuildLv* other);
  friend void swap(ReqUpBuildLv& a, ReqUpBuildLv& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqUpBuildLv* New() const final {
    return CreateMaybeMessage<ReqUpBuildLv>(NULL);
  }

  ReqUpBuildLv* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqUpBuildLv>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqUpBuildLv& from);
  void MergeFrom(const ReqUpBuildLv& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqUpBuildLv* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .NFMsg.Ident object_guid = 2;
  bool has_object_guid() const;
  void clear_object_guid();
  static const int kObjectGuidFieldNumber = 2;
  private:
  const ::NFMsg::Ident& _internal_object_guid() const;
  public:
  const ::NFMsg::Ident& object_guid() const;
  ::NFMsg::Ident* release_object_guid();
  ::NFMsg::Ident* mutable_object_guid();
  void set_allocated_object_guid(::NFMsg::Ident* object_guid);

  // optional int32 row = 1;
  bool has_row() const;
  void clear_row();
  static const int kRowFieldNumber = 1;
  ::google::protobuf::int32 row() const;
  void set_row(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NFMsg.ReqUpBuildLv)
 private:
  void set_has_row();
  void clear_has_row();
  void set_has_object_guid();
  void clear_has_object_guid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::NFMsg::Ident* object_guid_;
  ::google::protobuf::int32 row_;
  friend struct ::protobuf_NFSLGDefine_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqCreateItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NFMsg.ReqCreateItem) */ {
 public:
  ReqCreateItem();
  virtual ~ReqCreateItem();

  ReqCreateItem(const ReqCreateItem& from);

  inline ReqCreateItem& operator=(const ReqCreateItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqCreateItem(ReqCreateItem&& from) noexcept
    : ReqCreateItem() {
    *this = ::std::move(from);
  }

  inline ReqCreateItem& operator=(ReqCreateItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqCreateItem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqCreateItem* internal_default_instance() {
    return reinterpret_cast<const ReqCreateItem*>(
               &_ReqCreateItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ReqCreateItem* other);
  friend void swap(ReqCreateItem& a, ReqCreateItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqCreateItem* New() const final {
    return CreateMaybeMessage<ReqCreateItem>(NULL);
  }

  ReqCreateItem* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqCreateItem>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqCreateItem& from);
  void MergeFrom(const ReqCreateItem& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqCreateItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string config_id = 3;
  bool has_config_id() const;
  void clear_config_id();
  static const int kConfigIdFieldNumber = 3;
  const ::std::string& config_id() const;
  void set_config_id(const ::std::string& value);
  #if LANG_CXX11
  void set_config_id(::std::string&& value);
  #endif
  void set_config_id(const char* value);
  void set_config_id(const char* value, size_t size);
  ::std::string* mutable_config_id();
  ::std::string* release_config_id();
  void set_allocated_config_id(::std::string* config_id);

  // required .NFMsg.Ident object_guid = 2;
  bool has_object_guid() const;
  void clear_object_guid();
  static const int kObjectGuidFieldNumber = 2;
  private:
  const ::NFMsg::Ident& _internal_object_guid() const;
  public:
  const ::NFMsg::Ident& object_guid() const;
  ::NFMsg::Ident* release_object_guid();
  ::NFMsg::Ident* mutable_object_guid();
  void set_allocated_object_guid(::NFMsg::Ident* object_guid);

  // optional int32 row = 1;
  bool has_row() const;
  void clear_row();
  static const int kRowFieldNumber = 1;
  ::google::protobuf::int32 row() const;
  void set_row(::google::protobuf::int32 value);

  // required int32 count = 4;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 4;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NFMsg.ReqCreateItem)
 private:
  void set_has_row();
  void clear_has_row();
  void set_has_object_guid();
  void clear_has_object_guid();
  void set_has_config_id();
  void clear_has_config_id();
  void set_has_count();
  void clear_has_count();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr config_id_;
  ::NFMsg::Ident* object_guid_;
  ::google::protobuf::int32 row_;
  ::google::protobuf::int32 count_;
  friend struct ::protobuf_NFSLGDefine_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqBuildOperate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NFMsg.ReqBuildOperate) */ {
 public:
  ReqBuildOperate();
  virtual ~ReqBuildOperate();

  ReqBuildOperate(const ReqBuildOperate& from);

  inline ReqBuildOperate& operator=(const ReqBuildOperate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqBuildOperate(ReqBuildOperate&& from) noexcept
    : ReqBuildOperate() {
    *this = ::std::move(from);
  }

  inline ReqBuildOperate& operator=(ReqBuildOperate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqBuildOperate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqBuildOperate* internal_default_instance() {
    return reinterpret_cast<const ReqBuildOperate*>(
               &_ReqBuildOperate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ReqBuildOperate* other);
  friend void swap(ReqBuildOperate& a, ReqBuildOperate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqBuildOperate* New() const final {
    return CreateMaybeMessage<ReqBuildOperate>(NULL);
  }

  ReqBuildOperate* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqBuildOperate>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqBuildOperate& from);
  void MergeFrom(const ReqBuildOperate& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqBuildOperate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .NFMsg.Ident object_guid = 2;
  bool has_object_guid() const;
  void clear_object_guid();
  static const int kObjectGuidFieldNumber = 2;
  private:
  const ::NFMsg::Ident& _internal_object_guid() const;
  public:
  const ::NFMsg::Ident& object_guid() const;
  ::NFMsg::Ident* release_object_guid();
  ::NFMsg::Ident* mutable_object_guid();
  void set_allocated_object_guid(::NFMsg::Ident* object_guid);

  // optional int32 row = 1;
  bool has_row() const;
  void clear_row();
  static const int kRowFieldNumber = 1;
  ::google::protobuf::int32 row() const;
  void set_row(::google::protobuf::int32 value);

  // required .NFMsg.ESLGFuncType functype = 3;
  bool has_functype() const;
  void clear_functype();
  static const int kFunctypeFieldNumber = 3;
  ::NFMsg::ESLGFuncType functype() const;
  void set_functype(::NFMsg::ESLGFuncType value);

  // @@protoc_insertion_point(class_scope:NFMsg.ReqBuildOperate)
 private:
  void set_has_row();
  void clear_has_row();
  void set_has_object_guid();
  void clear_has_object_guid();
  void set_has_functype();
  void clear_has_functype();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::NFMsg::Ident* object_guid_;
  ::google::protobuf::int32 row_;
  int functype_;
  friend struct ::protobuf_NFSLGDefine_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqAckBuyObjectFormShop

// required string config_id = 1;
inline bool ReqAckBuyObjectFormShop::has_config_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReqAckBuyObjectFormShop::set_has_config_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReqAckBuyObjectFormShop::clear_has_config_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReqAckBuyObjectFormShop::clear_config_id() {
  config_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_config_id();
}
inline const ::std::string& ReqAckBuyObjectFormShop::config_id() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckBuyObjectFormShop.config_id)
  return config_id_.GetNoArena();
}
inline void ReqAckBuyObjectFormShop::set_config_id(const ::std::string& value) {
  set_has_config_id();
  config_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckBuyObjectFormShop.config_id)
}
#if LANG_CXX11
inline void ReqAckBuyObjectFormShop::set_config_id(::std::string&& value) {
  set_has_config_id();
  config_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NFMsg.ReqAckBuyObjectFormShop.config_id)
}
#endif
inline void ReqAckBuyObjectFormShop::set_config_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_config_id();
  config_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NFMsg.ReqAckBuyObjectFormShop.config_id)
}
inline void ReqAckBuyObjectFormShop::set_config_id(const char* value, size_t size) {
  set_has_config_id();
  config_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NFMsg.ReqAckBuyObjectFormShop.config_id)
}
inline ::std::string* ReqAckBuyObjectFormShop::mutable_config_id() {
  set_has_config_id();
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqAckBuyObjectFormShop.config_id)
  return config_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReqAckBuyObjectFormShop::release_config_id() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqAckBuyObjectFormShop.config_id)
  if (!has_config_id()) {
    return NULL;
  }
  clear_has_config_id();
  return config_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReqAckBuyObjectFormShop::set_allocated_config_id(::std::string* config_id) {
  if (config_id != NULL) {
    set_has_config_id();
  } else {
    clear_has_config_id();
  }
  config_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), config_id);
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqAckBuyObjectFormShop.config_id)
}

// required float x = 2;
inline bool ReqAckBuyObjectFormShop::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReqAckBuyObjectFormShop::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReqAckBuyObjectFormShop::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReqAckBuyObjectFormShop::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float ReqAckBuyObjectFormShop::x() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckBuyObjectFormShop.x)
  return x_;
}
inline void ReqAckBuyObjectFormShop::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckBuyObjectFormShop.x)
}

// required float y = 3;
inline bool ReqAckBuyObjectFormShop::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ReqAckBuyObjectFormShop::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ReqAckBuyObjectFormShop::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ReqAckBuyObjectFormShop::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float ReqAckBuyObjectFormShop::y() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckBuyObjectFormShop.y)
  return y_;
}
inline void ReqAckBuyObjectFormShop::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckBuyObjectFormShop.y)
}

// required float z = 4;
inline bool ReqAckBuyObjectFormShop::has_z() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ReqAckBuyObjectFormShop::set_has_z() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ReqAckBuyObjectFormShop::clear_has_z() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ReqAckBuyObjectFormShop::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float ReqAckBuyObjectFormShop::z() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckBuyObjectFormShop.z)
  return z_;
}
inline void ReqAckBuyObjectFormShop::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckBuyObjectFormShop.z)
}

// required string Shop_id = 5;
inline bool ReqAckBuyObjectFormShop::has_shop_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReqAckBuyObjectFormShop::set_has_shop_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReqAckBuyObjectFormShop::clear_has_shop_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReqAckBuyObjectFormShop::clear_shop_id() {
  shop_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shop_id();
}
inline const ::std::string& ReqAckBuyObjectFormShop::shop_id() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
  return shop_id_.GetNoArena();
}
inline void ReqAckBuyObjectFormShop::set_shop_id(const ::std::string& value) {
  set_has_shop_id();
  shop_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
}
#if LANG_CXX11
inline void ReqAckBuyObjectFormShop::set_shop_id(::std::string&& value) {
  set_has_shop_id();
  shop_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
}
#endif
inline void ReqAckBuyObjectFormShop::set_shop_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_shop_id();
  shop_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
}
inline void ReqAckBuyObjectFormShop::set_shop_id(const char* value, size_t size) {
  set_has_shop_id();
  shop_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
}
inline ::std::string* ReqAckBuyObjectFormShop::mutable_shop_id() {
  set_has_shop_id();
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
  return shop_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReqAckBuyObjectFormShop::release_shop_id() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
  if (!has_shop_id()) {
    return NULL;
  }
  clear_has_shop_id();
  return shop_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReqAckBuyObjectFormShop::set_allocated_shop_id(::std::string* shop_id) {
  if (shop_id != NULL) {
    set_has_shop_id();
  } else {
    clear_has_shop_id();
  }
  shop_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shop_id);
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqAckBuyObjectFormShop.Shop_id)
}

// -------------------------------------------------------------------

// ReqAckMoveBuildObject

// optional int32 row = 1;
inline bool ReqAckMoveBuildObject::has_row() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReqAckMoveBuildObject::set_has_row() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReqAckMoveBuildObject::clear_has_row() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReqAckMoveBuildObject::clear_row() {
  row_ = 0;
  clear_has_row();
}
inline ::google::protobuf::int32 ReqAckMoveBuildObject::row() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckMoveBuildObject.row)
  return row_;
}
inline void ReqAckMoveBuildObject::set_row(::google::protobuf::int32 value) {
  set_has_row();
  row_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckMoveBuildObject.row)
}

// required .NFMsg.Ident object_guid = 2;
inline bool ReqAckMoveBuildObject::has_object_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReqAckMoveBuildObject::set_has_object_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReqAckMoveBuildObject::clear_has_object_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::NFMsg::Ident& ReqAckMoveBuildObject::_internal_object_guid() const {
  return *object_guid_;
}
inline const ::NFMsg::Ident& ReqAckMoveBuildObject::object_guid() const {
  const ::NFMsg::Ident* p = object_guid_;
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckMoveBuildObject.object_guid)
  return p != NULL ? *p : *reinterpret_cast<const ::NFMsg::Ident*>(
      &::NFMsg::_Ident_default_instance_);
}
inline ::NFMsg::Ident* ReqAckMoveBuildObject::release_object_guid() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqAckMoveBuildObject.object_guid)
  clear_has_object_guid();
  ::NFMsg::Ident* temp = object_guid_;
  object_guid_ = NULL;
  return temp;
}
inline ::NFMsg::Ident* ReqAckMoveBuildObject::mutable_object_guid() {
  set_has_object_guid();
  if (object_guid_ == NULL) {
    auto* p = CreateMaybeMessage<::NFMsg::Ident>(GetArenaNoVirtual());
    object_guid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqAckMoveBuildObject.object_guid)
  return object_guid_;
}
inline void ReqAckMoveBuildObject::set_allocated_object_guid(::NFMsg::Ident* object_guid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(object_guid_);
  }
  if (object_guid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_guid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_guid, submessage_arena);
    }
    set_has_object_guid();
  } else {
    clear_has_object_guid();
  }
  object_guid_ = object_guid;
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqAckMoveBuildObject.object_guid)
}

// required float x = 3;
inline bool ReqAckMoveBuildObject::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReqAckMoveBuildObject::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReqAckMoveBuildObject::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReqAckMoveBuildObject::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float ReqAckMoveBuildObject::x() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckMoveBuildObject.x)
  return x_;
}
inline void ReqAckMoveBuildObject::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckMoveBuildObject.x)
}

// required float y = 4;
inline bool ReqAckMoveBuildObject::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ReqAckMoveBuildObject::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ReqAckMoveBuildObject::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ReqAckMoveBuildObject::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float ReqAckMoveBuildObject::y() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckMoveBuildObject.y)
  return y_;
}
inline void ReqAckMoveBuildObject::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckMoveBuildObject.y)
}

// required float z = 5;
inline bool ReqAckMoveBuildObject::has_z() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ReqAckMoveBuildObject::set_has_z() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ReqAckMoveBuildObject::clear_has_z() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ReqAckMoveBuildObject::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float ReqAckMoveBuildObject::z() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqAckMoveBuildObject.z)
  return z_;
}
inline void ReqAckMoveBuildObject::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqAckMoveBuildObject.z)
}

// -------------------------------------------------------------------

// ReqUpBuildLv

// optional int32 row = 1;
inline bool ReqUpBuildLv::has_row() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReqUpBuildLv::set_has_row() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReqUpBuildLv::clear_has_row() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReqUpBuildLv::clear_row() {
  row_ = 0;
  clear_has_row();
}
inline ::google::protobuf::int32 ReqUpBuildLv::row() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqUpBuildLv.row)
  return row_;
}
inline void ReqUpBuildLv::set_row(::google::protobuf::int32 value) {
  set_has_row();
  row_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqUpBuildLv.row)
}

// required .NFMsg.Ident object_guid = 2;
inline bool ReqUpBuildLv::has_object_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReqUpBuildLv::set_has_object_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReqUpBuildLv::clear_has_object_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::NFMsg::Ident& ReqUpBuildLv::_internal_object_guid() const {
  return *object_guid_;
}
inline const ::NFMsg::Ident& ReqUpBuildLv::object_guid() const {
  const ::NFMsg::Ident* p = object_guid_;
  // @@protoc_insertion_point(field_get:NFMsg.ReqUpBuildLv.object_guid)
  return p != NULL ? *p : *reinterpret_cast<const ::NFMsg::Ident*>(
      &::NFMsg::_Ident_default_instance_);
}
inline ::NFMsg::Ident* ReqUpBuildLv::release_object_guid() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqUpBuildLv.object_guid)
  clear_has_object_guid();
  ::NFMsg::Ident* temp = object_guid_;
  object_guid_ = NULL;
  return temp;
}
inline ::NFMsg::Ident* ReqUpBuildLv::mutable_object_guid() {
  set_has_object_guid();
  if (object_guid_ == NULL) {
    auto* p = CreateMaybeMessage<::NFMsg::Ident>(GetArenaNoVirtual());
    object_guid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqUpBuildLv.object_guid)
  return object_guid_;
}
inline void ReqUpBuildLv::set_allocated_object_guid(::NFMsg::Ident* object_guid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(object_guid_);
  }
  if (object_guid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_guid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_guid, submessage_arena);
    }
    set_has_object_guid();
  } else {
    clear_has_object_guid();
  }
  object_guid_ = object_guid;
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqUpBuildLv.object_guid)
}

// -------------------------------------------------------------------

// ReqCreateItem

// optional int32 row = 1;
inline bool ReqCreateItem::has_row() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReqCreateItem::set_has_row() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReqCreateItem::clear_has_row() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReqCreateItem::clear_row() {
  row_ = 0;
  clear_has_row();
}
inline ::google::protobuf::int32 ReqCreateItem::row() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqCreateItem.row)
  return row_;
}
inline void ReqCreateItem::set_row(::google::protobuf::int32 value) {
  set_has_row();
  row_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqCreateItem.row)
}

// required .NFMsg.Ident object_guid = 2;
inline bool ReqCreateItem::has_object_guid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReqCreateItem::set_has_object_guid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReqCreateItem::clear_has_object_guid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::NFMsg::Ident& ReqCreateItem::_internal_object_guid() const {
  return *object_guid_;
}
inline const ::NFMsg::Ident& ReqCreateItem::object_guid() const {
  const ::NFMsg::Ident* p = object_guid_;
  // @@protoc_insertion_point(field_get:NFMsg.ReqCreateItem.object_guid)
  return p != NULL ? *p : *reinterpret_cast<const ::NFMsg::Ident*>(
      &::NFMsg::_Ident_default_instance_);
}
inline ::NFMsg::Ident* ReqCreateItem::release_object_guid() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqCreateItem.object_guid)
  clear_has_object_guid();
  ::NFMsg::Ident* temp = object_guid_;
  object_guid_ = NULL;
  return temp;
}
inline ::NFMsg::Ident* ReqCreateItem::mutable_object_guid() {
  set_has_object_guid();
  if (object_guid_ == NULL) {
    auto* p = CreateMaybeMessage<::NFMsg::Ident>(GetArenaNoVirtual());
    object_guid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqCreateItem.object_guid)
  return object_guid_;
}
inline void ReqCreateItem::set_allocated_object_guid(::NFMsg::Ident* object_guid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(object_guid_);
  }
  if (object_guid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_guid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_guid, submessage_arena);
    }
    set_has_object_guid();
  } else {
    clear_has_object_guid();
  }
  object_guid_ = object_guid;
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqCreateItem.object_guid)
}

// required string config_id = 3;
inline bool ReqCreateItem::has_config_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReqCreateItem::set_has_config_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReqCreateItem::clear_has_config_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReqCreateItem::clear_config_id() {
  config_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_config_id();
}
inline const ::std::string& ReqCreateItem::config_id() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqCreateItem.config_id)
  return config_id_.GetNoArena();
}
inline void ReqCreateItem::set_config_id(const ::std::string& value) {
  set_has_config_id();
  config_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NFMsg.ReqCreateItem.config_id)
}
#if LANG_CXX11
inline void ReqCreateItem::set_config_id(::std::string&& value) {
  set_has_config_id();
  config_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NFMsg.ReqCreateItem.config_id)
}
#endif
inline void ReqCreateItem::set_config_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_config_id();
  config_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NFMsg.ReqCreateItem.config_id)
}
inline void ReqCreateItem::set_config_id(const char* value, size_t size) {
  set_has_config_id();
  config_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NFMsg.ReqCreateItem.config_id)
}
inline ::std::string* ReqCreateItem::mutable_config_id() {
  set_has_config_id();
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqCreateItem.config_id)
  return config_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReqCreateItem::release_config_id() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqCreateItem.config_id)
  if (!has_config_id()) {
    return NULL;
  }
  clear_has_config_id();
  return config_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReqCreateItem::set_allocated_config_id(::std::string* config_id) {
  if (config_id != NULL) {
    set_has_config_id();
  } else {
    clear_has_config_id();
  }
  config_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), config_id);
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqCreateItem.config_id)
}

// required int32 count = 4;
inline bool ReqCreateItem::has_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ReqCreateItem::set_has_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ReqCreateItem::clear_has_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ReqCreateItem::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 ReqCreateItem::count() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqCreateItem.count)
  return count_;
}
inline void ReqCreateItem::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqCreateItem.count)
}

// -------------------------------------------------------------------

// ReqBuildOperate

// optional int32 row = 1;
inline bool ReqBuildOperate::has_row() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReqBuildOperate::set_has_row() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReqBuildOperate::clear_has_row() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReqBuildOperate::clear_row() {
  row_ = 0;
  clear_has_row();
}
inline ::google::protobuf::int32 ReqBuildOperate::row() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqBuildOperate.row)
  return row_;
}
inline void ReqBuildOperate::set_row(::google::protobuf::int32 value) {
  set_has_row();
  row_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqBuildOperate.row)
}

// required .NFMsg.Ident object_guid = 2;
inline bool ReqBuildOperate::has_object_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReqBuildOperate::set_has_object_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReqBuildOperate::clear_has_object_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::NFMsg::Ident& ReqBuildOperate::_internal_object_guid() const {
  return *object_guid_;
}
inline const ::NFMsg::Ident& ReqBuildOperate::object_guid() const {
  const ::NFMsg::Ident* p = object_guid_;
  // @@protoc_insertion_point(field_get:NFMsg.ReqBuildOperate.object_guid)
  return p != NULL ? *p : *reinterpret_cast<const ::NFMsg::Ident*>(
      &::NFMsg::_Ident_default_instance_);
}
inline ::NFMsg::Ident* ReqBuildOperate::release_object_guid() {
  // @@protoc_insertion_point(field_release:NFMsg.ReqBuildOperate.object_guid)
  clear_has_object_guid();
  ::NFMsg::Ident* temp = object_guid_;
  object_guid_ = NULL;
  return temp;
}
inline ::NFMsg::Ident* ReqBuildOperate::mutable_object_guid() {
  set_has_object_guid();
  if (object_guid_ == NULL) {
    auto* p = CreateMaybeMessage<::NFMsg::Ident>(GetArenaNoVirtual());
    object_guid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:NFMsg.ReqBuildOperate.object_guid)
  return object_guid_;
}
inline void ReqBuildOperate::set_allocated_object_guid(::NFMsg::Ident* object_guid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(object_guid_);
  }
  if (object_guid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_guid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_guid, submessage_arena);
    }
    set_has_object_guid();
  } else {
    clear_has_object_guid();
  }
  object_guid_ = object_guid;
  // @@protoc_insertion_point(field_set_allocated:NFMsg.ReqBuildOperate.object_guid)
}

// required .NFMsg.ESLGFuncType functype = 3;
inline bool ReqBuildOperate::has_functype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReqBuildOperate::set_has_functype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReqBuildOperate::clear_has_functype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReqBuildOperate::clear_functype() {
  functype_ = 0;
  clear_has_functype();
}
inline ::NFMsg::ESLGFuncType ReqBuildOperate::functype() const {
  // @@protoc_insertion_point(field_get:NFMsg.ReqBuildOperate.functype)
  return static_cast< ::NFMsg::ESLGFuncType >(functype_);
}
inline void ReqBuildOperate::set_functype(::NFMsg::ESLGFuncType value) {
  assert(::NFMsg::ESLGFuncType_IsValid(value));
  set_has_functype();
  functype_ = value;
  // @@protoc_insertion_point(field_set:NFMsg.ReqBuildOperate.functype)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace NFMsg

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::NFMsg::ESLGBuildingType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFMsg::ESLGBuildingType>() {
  return ::NFMsg::ESLGBuildingType_descriptor();
}
template <> struct is_proto_enum< ::NFMsg::ESLGBuildingSubType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFMsg::ESLGBuildingSubType>() {
  return ::NFMsg::ESLGBuildingSubType_descriptor();
}
template <> struct is_proto_enum< ::NFMsg::ESLGArmyType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFMsg::ESLGArmyType>() {
  return ::NFMsg::ESLGArmyType_descriptor();
}
template <> struct is_proto_enum< ::NFMsg::ESLGFuncType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFMsg::ESLGFuncType>() {
  return ::NFMsg::ESLGFuncType_descriptor();
}
template <> struct is_proto_enum< ::NFMsg::ESLGBuildingState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFMsg::ESLGBuildingState>() {
  return ::NFMsg::ESLGBuildingState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_NFSLGDefine_2eproto
